src/Entity/ServiceItem.php
<?php

namespace App\Entity;

use App\UserInterface\EntityPriceSortableInterface;
use App\Repository\ServiceItemRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ServiceItemRepository::class)]
class ServiceItem implements EntityPriceSortableInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 400)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $price = null;

    #[ORM\ManyToOne(inversedBy: 'serviceItems')]
    private ?Service $Service = null;

    #[ORM\OneToMany(mappedBy: 'serviceItemMap', targetEntity: ServiceItemSubscriptionService::class, cascade: ['remove'], orphanRemoval: true)]
    private Collection $serviceItemSubscriptionServices;

    public function __construct()
    {
        $this->serviceItemSubscriptionServices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->Service;
    }

    public function setService(?Service $Service): self
    {
        $this->Service = $Service;

        return $this;
    }

    /**
     * @return Collection<int, ServiceItemSubscriptionService>
     */
    public function getServiceItemSubscriptionServices(): Collection
    {
        return $this->serviceItemSubscriptionServices;
    }
    
    public function getIntPrice(): int
    {

        $price_str = $this->getPrice();
        if(str_contains(mb_strtolower($price_str), "договор"))
        {
            return PHP_INT_MAX;
        }

        if(preg_replace("/[^0-9]/", "", $price_str) == "")
        {
            return 0;
        }

        $price_str = preg_replace("/[^0-9\,\.]/", "", $price_str);
        return intval(floatval($price_str));
    }

}

src/Entity/SubscriptionService.php
<?php

namespace App\Entity;

use App\UserInterface\EntityPriceSortableInterface;
use App\Repository\SubscriptionServiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SubscriptionServiceRepository::class)]
class SubscriptionService implements EntityPriceSortableInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $price = null;

    #[ORM\Column(length: 255)]
    private ?string $img = null;

    #[ORM\OneToMany(mappedBy: 'subscriptionServiceMap', targetEntity: ServiceItemSubscriptionService::class, cascade: ['remove'], orphanRemoval: true)]
    private Collection $serviceItemSubscriptionServices;

    #[ORM\Column(length: 255)]
    private ?string $subTitle = null;

    public function __construct()
    {
        $this->serviceItemSubscriptionServices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): self
    {
        $this->img = $img;

        return $this;
    }

    /**
     * @return Collection<int, ServiceItemSubscriptionService>
     */
    public function getServiceItemSubscriptionServices(): Collection
    {
        return $this->serviceItemSubscriptionServices;
    }

    public function getSubTitle(): ?string
    {
        return $this->subTitle;
    }

    public function setSubTitle(string $subTitle): self
    {
        $this->subTitle = $subTitle;

        return $this;
    }


    public function getIntPrice(): int
    {

        $price_str = $this->getPrice();
        if(str_contains(mb_strtolower($price_str), "договор"))
        {
            return PHP_INT_MAX;
        }

        if(preg_replace("/[^0-9]/", "", $price_str) == "")
        {
            return 0;
        }

        $price_str = preg_replace("/[^0-9\,\.]/", "", $price_str);
        return intval(floatval($price_str));
    }

}

src/Controller/SubscriptionServiceController.php
<?php

namespace App\Controller;

use App\Entity\Person;
use App\Entity\Review;
use App\Entity\Service;
use App\Entity\ServiceItem;
use App\Entity\ServiceItemSubscriptionService;
use App\Entity\SubscriptionService;
use App\Utils\ImgUploader;
use App\Utils\JsonBlockLoader;
use App\Utils\PaginateHelper;
use App\Utils\SEOHelper;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Routing\Annotation\Route;

class SubscriptionServiceController extends AbstractController
{
    #[Route('/subscription_services', name: 'subscription_services', methods:["GET"])]
    public function index(Request $request, ManagerRegistry $doctrine, JsonBlockLoader $jsonBlockLoader): Response
    {
        $json_blocks =  $jsonBlockLoader->load($doctrine);
        
        return $this->render('user/subscription_services/index.html.twig', [
            'json_blocks' => $json_blocks,
            'seo' => SEOHelper::getSEOFromJsonBlockData($json_blocks, "subscription_services", "article"),
            'reviews_banner' => $doctrine->getRepository(Review::class)->findRandom(20) ,
            'service_banner' => $doctrine->getRepository(Service::class)->findRandom(20),
            'persons_banner' => $doctrine->getRepository(Person::class)->findTopRank(3),
            'subscription_services' => $doctrine->getRepository(SubscriptionService::class)->findAll() 
        ]
       );

    }

    #[Route('/subscription_services/{id}', name: 'subscription_services_view', methods:["GET"])]
    public function view(int $id, ManagerRegistry $doctrine, JsonBlockLoader $jsonBlockLoader): Response
    {
        $json_blocks =  $jsonBlockLoader->load($doctrine);

        $repository = $doctrine->getRepository(SubscriptionService::class);
        $subscriptionService = $repository->find($id);
        
        if(!$subscriptionService)
        { 
            throw $this->createNotFoundException(  );
        }

        $serviceItems = \iterator_to_array($subscriptionService->getServiceItemSubscriptionServices());
        usort($serviceItems, fn ($a, $b) => intval($a->getId() > $b->getId()));

        $description = "Пакет абонентского обслуживания \"" .$subscriptionService->getName() . "\". ". mb_substr($subscriptionService->getDescription(), 0, 160);

        
        return $this->render('user/subscription_services/view.html.twig', [
            'json_blocks' => $json_blocks,
            'subscription_service' => $subscriptionService,
            'service_items' => $serviceItems,
            'reviews_banner' => $doctrine->getRepository(Review::class)->findRandom(20),
            'service_banner' => $doctrine->getRepository(Service::class)->findRandom(20),
            'persons_banner' => $doctrine->getRepository(Person::class)->findTopRank(3),
            'seo' => SEOHelper::getSEOFromData(
                $subscriptionService->getName() . " - ". "пакет абонентского обслуживания", 
                $description, 
                "subscription_services/".$subscriptionService->getId(), 
                "article",
                "files/subscription_services/200_w/". $subscriptionService->getImg()),
        ]
       );

    }


    #[Route('/admin/subscription_services', name: 'admin_subscription_services', methods:["GET"])]
    public function adminIndex(Request $request, ManagerRegistry $doctrine): Response
    {
        $paginateHelper = PaginateHelper::createFormRequest($request,8);

        $subscriptionServiceRepository = $doctrine->getRepository(SubscriptionService::class);
        $paginator = $subscriptionServiceRepository->getListPaginator($paginateHelper);
        
        return $this->render('admin/subscription_services/index.html.twig', [
            'title' => 'Абонентское обслуживание',
            'files_dir' => 'subscription_services',
            'subscription_services' => $paginator 
        ] + $paginateHelper -> getViewInfo($subscriptionServiceRepository->getNum(), 10)
       );

    }

    #[Route('/admin/subscription_services/form', methods:["GET"], name:'subscription_service_form_new')]
    public function addForm(Request $request): Response
    { 
        $query_params = $request->query;

        $err = ($query_params->has('err'))? boolval($query_params->get('err')): false;
        $error_text = ($query_params->has('error_text'))? $query_params->get('error_text'): false;

        return $this->render('admin/subscription_services/form_new.html.twig', [
            'title' => 'Добавить новый пакет абонентского обслуживания',
            'error' => $err,
            'error_text' => $error_text
        ]);
    }

    #[Route('/admin/subscription_services', methods:["POST"])]
    public function add(Request $request,  ManagerRegistry $doctrine): Response
    { 
        $input = $request->request;
        $file = $request->files;

        try
        {
            if( !( $input->has('name') && 
                   $input->has('sub_title') && 
                   $input->has('description') && 
                   $input->has('price') && 
                   $file->has('file') && 
                   !is_null($file->get('file'))))
            {
                throw new BadRequestHttpException("Не переданы обязательные данные");
            }

            $subscriptionService = new SubscriptionService();
            $subscriptionService->setName($input->get('name'));
            $subscriptionService->setSubTitle($input->get('sub_title'));
            $subscriptionService->setDescription($input->get('description'));
            $subscriptionService->setPrice($input->get('price'));
            $uploader = new ImgUploader($file->get('file'), 'files/subscription_services', ImgUploader::$JPEG_PNG_MIME);
            $uploader->loadImg(560, 460, 1.4, 0.6);
            $uploader->saveImg([100, 200, 560]);

            $subscriptionService->setImg($uploader->getPath());

            $doctrine->getRepository(SubscriptionService::class)->save($subscriptionService, true);

            return $this->redirectToRoute('admin_subscription_services'); 

        } catch( BadRequestHttpException | FileException $err)
        {

            return $this->redirectToRoute(
                'subscription_service_form_new',
                ['err' => 1, 'error_text' => $err->getMessage()]
            );
        }
    }

    #[Route('/admin/subscription_services/{id}', methods:["GET"], name:'subscription_service_form_update')]
    public function updateForm(int $id, Request $request, ManagerRegistry $doctrine): Response
    {
        $repository = $doctrine->getRepository(SubscriptionService::class);
        $subscriptionService = $repository->find($id);
        
        if(!$subscriptionService)
        { 
            throw $this->createNotFoundException( 'Нет абонентского обслуживания с id = '.$id.'!' );
        }

        $serviceItems = \iterator_to_array($subscriptionService->getServiceItemSubscriptionServices());
        if( !count($serviceItems))
        {
            $otherItems = $doctrine->getRepository(ServiceItem::class)->findAll();

        } else
        {
            $ids = array_map( fn($x) : int => $x->getServiceItemMap()->getId() ,$serviceItems);
            $otherItems = $doctrine->getRepository(ServiceItem::class)->findByExludeIds($ids);
            usort($serviceItems, fn ($a, $b) => $a->getId() > $b->getId());
        }
        usort($otherItems, fn ($a, $b) => strcmp($a->getName(), $b->getName()));
        $query_params = $request->query;
        $err = ($query_params->has('err'))? boolval($query_params->get('err')): false;
        $success = ($query_params->has('success'))? boolval($query_params->get('success')): false;
        $success_sub_id = ($query_params->has('success_sub_id'))? $query_params->get('success_sub_id'): 0;
        $error_text = ($query_params->has('error_text'))? $query_params->get('error_text'): false;;

        return $this->render('admin/subscription_services/form_update.html.twig', [
            'title' => 'Пакет абонентского обслуживания: "'.$subscriptionService->getName().'"',
            'subscription_service' => $subscriptionService,
            'service_items' => $serviceItems,
            'other_items' => $otherItems,
            'files_dir' => 'subscription_services',
            'success_sub_id' => $success_sub_id,
            'error' => $err,
            'success' => $success ,
            'error_text' => $error_text
        ]);
    }


    #[Route('/admin/subscription_services/{id}', methods:["PUT", "POST"])]
    public function updateSubscriptionService(int $id,  Request $request, ManagerRegistry $doctrine): Response
    {
        $input = $request->request;
        $file = $request->files;

        $entityManager = $doctrine->getManager();

        try
        {
            if( !( $input->has('name') && 
                   $input->has('sub_title') && 
                   $input->has('description') && 
                   $input->has('price')))
            {
                throw new BadRequestHttpException("Не переданы обязательные данные");
            }

            $subscriptionService = $entityManager->getRepository(SubscriptionService::class)->find($id);

            if(!$subscriptionService)
            { 
                throw $this->createNotFoundException( 'Нет абонентского обслуживания с id = '.$id.'!' );
            }

            if($file->has('file') && !is_null($file->get('file')))
            {
                $file = $request->files->get('file');
                $uploader = new ImgUploader($file, 'files/subscription_services', ImgUploader::$JPEG_PNG_MIME);

templates/user/subscription_services/index.html.twig
{{ include('user/common/header.html.twig') }}
{{ include('user/common/subheader.html.twig', {breadcrumbs: [{name: "Главная", "link": ""},{name: "Абонентское обслуживание", "link": "subscription_services"} ]}) }}
{{ include('user/common/title.html.twig', {title: json_blocks.titles.subscription_services.title, subtitle: json_blocks.titles.subscription_services.sub_title})}}
<div class="content_wrapper subscription_services">

        <p class="subscription_services_description">{{json_blocks.page_subscription_info.description}}</p>
            <a name="subscription_services"></a>
        <div class="subscription_services_wrapper subscription_services_common_wrapper">

            {% for index, subscription_service in subscription_services %}
            <div class="subscription_services_item item">
                <div class="name">
                        <a href="{{ site_url }}/subscription_services/{{subscription_service.id}}">{{subscription_service.name}}</a>
                        <div class="underline"></div>
                </div>
                <div class="description">
                        {{subscription_service.subTitle}}
                </div>
                <div class="price">{{subscription_service.price}}</div>
                <div class="button"><a href="{{ site_url }}/subscription_services/{{subscription_service.id}}">➔</a></div>
            </div>
        {% endfor %}
            
        </div>
</div>
        <div class="warp_1_5p"></div>
{{ include('user/common/persons.html.twig') }}
        <div class="warp_1_5p"></div>
{{ include('user/common/request.html.twig') }}
        <div class="warp_1_5p"></div>
{{ include('user/common/services.html.twig') }}
{{ include('user/common/reviews.html.twig') }}
{{ include('user/common/footer.html.twig') }}

templates/user/subscription_services/view.html.twig
{{ include('user/common/header.html.twig') }}
{{ include('user/common/subheader.html.twig', {breadcrumbs: [{name: "Главная", "link": ""},{name: "Абонентское обслуживание", "link": "subscription_services"} ]}) }}
{{ include('user/common/title.html.twig', {title: subscription_service.name, subtitle: 'Пакет'})}}



<div class="subscription_services_description_title_wrapper"><div><h2>Описание услуги</h2></div></div>
<div class="content_wrapper subscription_services_view">

    <div class="item_wrapper">
        <div class="item left_block_wrappeer">
            <p>{{subscription_service.description| nl2br}}</p>
        </div>
        <div class="item right_block_wrapper">
        <img src="{{site_url}}/files/subscription_services/560_w/{{subscription_service.img}}" alt="{{subscription_service.name}}" title="{{subscription_service.name}}">
            <div class="price_info">
            <span class="price_label">Стоимость</span>
            <span class="price_amout">{{subscription_service.price}}</span>
            <a data-hystmodal="#request_modal">Заказать</a>
            </div>
        </div>
    </div>
    <div class="subscription_services_list_wrapper">
        <input type="checkbox" id="toggle-1" class="open_hide_checkbox">
        <label for="toggle-1" class="open_hide">Что входит в пакет?<span class="arrow_wrapper_2"><span class="arrow_wrapper">▲</span></span></label>
        <div class="checkbox_wrapper subscription_services_list">
        {% for item in service_items %}
        <a href="{{site_url}}/services/{{item.serviceItemMap.service.type.value}}/{{item.serviceItemMap.service.canonicalUrl}}#{{item.serviceItemMap.id}}" ><span class="service_name">{{item.serviceItemMap.name}}</span><span class="service_amount">{{item.amount}}</span></a>
        {% endfor %}
        </div>
    </div>
</div>


        <div class="warp_1_5p"></div>
{{ include('user/common/persons.html.twig') }}
        <div class="warp_1_5p"></div>
{{ include('user/common/request.html.twig') }}
        <div class="warp_1_5p"></div>
{{ include('user/common/services.html.twig') }}
{{ include('user/common/reviews.html.twig') }}
{{ include('user/common/footer.html.twig') }}